import Head from "next/head";
import Header from "@/components/Header";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex justify-center items-center h-[80vh]">
          <h1 className="text-bold text-xl text-green-500">
            <div>This is a private blog app</div>
          </h1>
        </div>
      </main>
    </>
  );
}
